name: Build Program
 
on: 
  push:
    branches: ["main"]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v2
  
    - name: Setup NuGet
    - uses: nuget/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore MSIFanControl.sln
 
    - name: Build Solution
      run: |
        msbuild.exe MSIFanControl.sln /nologo /nr:false /p:DeployOnBuild=true /p:platform="Any CPU" /p:configuration="$env:Configuration"
      env:
        Configuration: ${{ matrix.Configuration }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: "MSIFanControl-${{ matrix.Configuration }}"
        path: "./MSIFanControl.GUI/bin/${{ matrix.Configuration }}/"
        compression-level: 9
